### ISSUE TITLE
Marketing Tracking

### ISSUE THREAD

**Issue by a0m0rajab** [a0m0rajab/Reddit_Chat_Shredeer#1]
- [x] logo
- [x] Chrome store 
- [ ] Twitter video 
- [ ] Article (dev.to) 
- [ ] Reddit Shreddit stuff
- [ ] Awesome Open Source repos

**Comment by a0m0rajab** [comment]
Logo: [deaddit](https://www.reddit.com/r/sbubby/comments/9c6xz3/deaddit/)

![Logo](https://github.com/a0m0rajab/Reddit_Chat_Shredeer/assets/18273833/45e0dabc-f166-4a84-9125-c33cd788a170)

Chrome Store Screenshot: 

![Reddit Chat Shredder](https://github.com/a0m0rajab/Reddit_Chat_Shredeer/assets/18273833/0a7c3a2e-f08a-40a0-be36-395bcc8f1501)

**Comment by a0m0rajab** [comment]
Store screenshot: 
![Reddit Chat Shredder - Copy](https://github.com/a0m0rajab/Reddit_Chat_Shredeer/assets/18273833/2b94e8dc-081f-4bfd-81cf-8ccbcef1ff26)
